services:
  # 1. Backend (API Node.js + MongoDB)
  - type: web
    name: journey-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://felipe008lucas:Fe535356%40@cluster0.rl5twua.mongodb.net/journey_db?appName=Cluster0"

  # 2. Frontend (React Site)
  - type: web
    name: journey-frontend
    env: static
    rootDir: react-journey
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "https://journey-backend-3dnr.onrender.com/api"
      - key: VITE_DELIVERY_API_URL
        value: "https://journey-backend-3dnr.onrender.com/api/delivery"
