// <auto-generated />
using Bora.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bora.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202111849_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Bora.API.Models.DiaTrabalho", b =>
                {
                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entrada")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ganhos")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GastoAntecipacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GastoGasolina")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GastoManutencao")
                        .HasColumnType("TEXT");

                    b.Property<double>("KmFinal")
                        .HasColumnType("REAL");

                    b.Property<double>("KmInicial")
                        .HasColumnType("REAL");

                    b.Property<double>("KmRodados")
                        .HasColumnType("REAL");

                    b.Property<bool>("MetaBatida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Saida")
                        .HasColumnType("TEXT");

                    b.HasKey("Data");

                    b.ToTable("Dias");
                });
#pragma warning restore 612, 618
        }
    }
}
